/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CAMERAFLASH_AUTODEFS_H
#define CAMERAFLASH_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CAMERAFLASH_NAME "CameraFlash"
#define S3E_EXT_CAMERAFLASH_HASH 0x66012dc

#endif /* !CAMERAFLASH_AUTODEFS_H */
