/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "CameraFlash_autodefs.h"
#include "s3eEdk.h"
#include "CameraFlash.h"
//Declarations of Init and Term functions
extern s3eResult CameraFlashInit();
extern void CameraFlashTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void TurnFlashOn_wrap(bool turnOn)
{
    IwTrace(CAMERAFLASH_VERBOSE, ("calling CameraFlash func on main thread: TurnFlashOn"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)TurnFlashOn, 1, turnOn);
}

static void TurnFlashOff_wrap()
{
    IwTrace(CAMERAFLASH_VERBOSE, ("calling CameraFlash func on main thread: TurnFlashOff"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)TurnFlashOff, 0);
}

#define TurnFlashOn TurnFlashOn_wrap
#define TurnFlashOff TurnFlashOff_wrap

#endif

s3eResult CameraFlashRegister(CameraFlashCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_CAMERAFLASH_HASH, CAMERAFLASH_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult CameraFlashUnRegister(CameraFlashCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_CAMERAFLASH_HASH, CAMERAFLASH_CALLBACK_MAX, cbid, fn);
}

void CameraFlashRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[4];
    funcPtrs[0] = (void*)CameraFlashRegister;
    funcPtrs[1] = (void*)CameraFlashUnRegister;
    funcPtrs[2] = (void*)TurnFlashOn;
    funcPtrs[3] = (void*)TurnFlashOff;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[4] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("CameraFlash", funcPtrs, sizeof(funcPtrs), flags, CameraFlashInit, CameraFlashTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int CameraFlashStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&CameraFlashRegisterExt;
    return 0;
}

int g_CameraFlashVal = CameraFlashStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    CameraFlashRegisterExt();
}
#endif

#endif
