/*
 * Copyright (C) 2001-2012 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_CAMERAFLASH_H
#define S3E_EXT_CAMERAFLASH_H

#include "s3eTypes.h"
typedef enum CameraFlashCallback
{
    CAMERAFLASH_CALLBACK_DUMMY,
    CAMERAFLASH_CALLBACK_MAX
} CameraFlashCallback;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the CameraFlash extension is available.
 */
s3eBool CameraFlashAvailable();

/**
 * Registers a callback to be called for an operating system event.
 *
 * The available callback types are listed in @ref CameraFlashCallback.
 * @param cbid ID of the event for which to register.
 * @param fn callback function.
 * @param userdata Value to pass to the @e userdata parameter of @e NotifyFunc.
 * @return
 *  - @ref S3E_RESULT_SUCCESS if no error occurred.
 *  - @ref S3E_RESULT_ERROR if the operation failed.\n
 *
 * @see CameraFlashUnRegister
 * @note For more information on the system data passed as a parameter to the callback
 * registered using this function, see the @ref CameraFlashCallback enum.
 */
s3eResult CameraFlashRegister(CameraFlashCallback cbid, s3eCallback fn, void* userData);

/**
 * Unregister a callback for a given event.
 * @param cbid ID of the callback for which to register.
 * @param fn Callback Function.
 * @return
 * - @ref S3E_RESULT_SUCCESS if no error occurred.
 * - @ref S3E_RESULT_ERROR if the operation failed.\n
 * @note For more information on the systemData passed as a parameter to the callback
 * registered using this function, see the CameraFlashCallback enum.
 * @note It is not necessary to define a return value for any registered callback.
 * @see CameraFlashRegister
 */
s3eResult CameraFlashUnRegister(CameraFlashCallback cbid, s3eCallback fn);

void TurnFlashOn(bool turnOn);

void TurnFlashOff();

S3E_END_C_DECL

#endif /* !S3E_EXT_CAMERAFLASH_H */
